// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.34209
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace FagdagCqrs.Specs.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Kunde reserverer et rom")]
    public partial class KundeReservererEtRomFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "KundeReservererEtRom.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("nb-NO"), "Kunde reserverer et rom", @"Som kunde ønsker jeg å reservere en romtype
skal kunne reservere for 1 til n dager ved et gitt hotel med en angitt romtype
skal se totalprisen før bestillingen bekreftes

jeg skal få en bekreftelse på bestillingen på mail
det skal reserveres et beløp som tilsvarer 50% av totalprisen på rommet på min bankkonto", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Reservere rom av en gitt type skal se totalpris før jeg bekrefter")]
        public virtual void ReservereRomAvEnGittTypeSkalSeTotalprisForJegBekrefter()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Reservere rom av en gitt type skal se totalpris før jeg bekrefter", ((string[])(null)));
#line 9
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Romtype",
                        "Fra dato",
                        "Lengde på opphold"});
            table1.AddRow(new string[] {
                        "Junior Suite",
                        "20-1-2015",
                        "5"});
#line 10
 testRunner.When("jeg reserverer et rom", ((string)(null)), table1, "Når ");
#line 13
 testRunner.Then("skal jeg se totalprisen før bestillingen bekreftes", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Så ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Reservere rom av en gitt type skal se reservasjon i listen")]
        public virtual void ReservereRomAvEnGittTypeSkalSeReservasjonIListen()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Reservere rom av en gitt type skal se reservasjon i listen", ((string[])(null)));
#line 15
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Romtype",
                        "Fra dato",
                        "Lengde på opphold"});
            table2.AddRow(new string[] {
                        "Junior Suite",
                        "20-1-2015",
                        "5"});
#line 16
 testRunner.When("jeg reserverer et rom", ((string)(null)), table2, "Når ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Romtype",
                        "Fra dato",
                        "Lengde på opphold"});
            table3.AddRow(new string[] {
                        "Junior Suite",
                        "20-1-2015",
                        "5"});
#line 19
 testRunner.Then("skal jeg se reservasjonen i reservasjons listen", ((string)(null)), table3, "Så ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
